# Generated by Django 4.2 on 2023-04-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Modeli')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
            ],
        ),
    ]
